CREATE TABLE USERS(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(55) NOT NULL,
	type CHAR(1) NOT NULL,
	password VARCHAR(30) NOT NULL,
	nickname VARCHAR(30) NOT NULL,
	avatar VARCHAR(30) NOT NULL
);

CREATE TABLE ALBUM(
	id INT AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	idUser INT,
	FOREIGN KEY (idUser) REFERENCES USERS(id) ON DELETE CASCADE,
	PRIMARY KEY(id,idUser)
);

CREATE TABLE IMAGE(
	id INT AUTO_INCREMENT PRIMARY KEY,
	prop INT NOT NULL,
	title VARCHAR(50) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	photo VARCHAR(500) NOT NULL
);

CREATE TABLE IMAGEXALBUM(
	idAlbum INT,
	idImage INT,
	orderNumber INT NOT NULL,
	FOREIGN KEY (idAlbum) REFERENCES ALBUM(id) ON DELETE CASCADE,
	FOREIGN KEY (idImage) REFERENCES IMAGE(id) ON DELETE CASCADE,
	PRIMARY KEY(idAlbum,idImage)
);

CREATE TABLE COMMENTARY(
	id INT AUTO_INCREMENT PRIMARY KEY,
	author VARCHAR(55) NOT NULL,
	idUser INT,
	idImage INT,
	description VARCHAR(1000) NOT NULL,
	FOREIGN KEY (idUser) REFERENCES USERS(id) ON DELETE CASCADE,
	FOREIGN KEY (idImage) REFERENCES IMAGE(id) ON DELETE CASCADE
	
);

ALTER TABLE `users` ADD UNIQUE( `nickname`);